### ISSUE TITLE
[hotfix] 기능 수정

### ISSUE THREAD

**Issue by rivkode** [TeamSynergyy/synergy_be#40]
## To-do

- [ ] 신청기능
  - [ ] 나의신청내역 조회시 PROCESS조건추가
  - [ ] 예외처리 변경
- [ ] 게시글 응답 수정 기능
  - [ ] 속성 isNext -> hasNext로 변경
  - [ ] likes 초기화
- [ ] 댓글 알림 기능
- [ ] 티켓 기능
  - [ ] 티켓 할당 유저 제거
  - [ ] 티켓 위치변경, 수정 로직 분리
