### ISSUE TITLE
[feature] 스프링부트 2.xx -> 3.1.5 / 자바 11 -> 17 마이그레이션

### ISSUE THREAD

**Issue by rivkode** [TeamSynergyy/synergy_be#55]
## 📌 Feature Issue

스프링부트 버전을 2.7.15 -> 3.1.5 로 마이그레이션을 진행합니다.

자바 버전을 11 -> 17 로 마이그레이션을 진행합니다.

마이그레이션 진행시 고려할 점과 이유에 대해 작성합니다.

## To-do

- [x] 자바 버전 번경
- [x] 스프링부트 버전 번경
- [x] 고려사항 작성
- [x] 이유 작성
- [x] Spring boot Security 변경
