### ISSUE TITLE
[feature] 프로젝트

### ISSUE THREAD

**Issue by rivkode** [TeamSynergyy/synergy_be#6]
### 해당 이슈를 1줄로 요약

**프로젝트 `생성`, `추천 받기`, `지원` 이(가) 가능하다**

---

<br>

프로젝트 기능

- 프로젝트
    - CRUD
    - 추천 프로젝트 리스트 (fast API 서버로부터 받아옴)
    - 수정일 기준 최신순 프로젝트 가져오기
    - 키워드 검색 (Like문 사용)
    - 좋아요한 프로젝트 리스트

- 프로젝트 지원
    - CRUD
    - 승인
    - 거절

## To-do

- [ ] 프로젝트 진행 위치 좌표 DB 설정 (DBSpatial, Point 사용)
- [ ] 요구사항 query 작성
- [ ] 키워드 검색 기능 구현
- [ ] 다른 Docker 컨테이너 (fast API) 로부터 데이터 요청, 응답 구현
- [ ] 프로젝트 지원자에 대한 승인, 거절 구현
