### ISSUE TITLE
[feature] 유저 엔티티 임베디드 타입 적용 / 회원가입 수정

### ISSUE THREAD

**Issue by rivkode** [TeamSynergyy/synergy_be#61]
## To-do

- [x] 비밀번호 생성시 암호화
- [x] 이메일 검증 로직 추가
- [x] userSeq 제거
- [x] userId 타입 String -> Long 변경
