### ISSUE TITLE
회원가입시 이메일 인증 기능

### ISSUE THREAD

**Issue by rivkode** [TeamSynergyy/synergy_be#97]
## To-do

- [x] 이메일 전송 기능
- [x] 랜덤 상수 생성 기능
- [x] Redis 관련 설정

아래와 같이 이메일 적용 완료

![image](https://github.com/TeamSynergyy/synergy_be/assets/109144975/c4e33b48-3d00-46bc-a073-40bacce3eb87)
