### ISSUE TITLE
지속 성장 가능한 소프트웨어 - 게시글 도메인

### ISSUE THREAD

**Issue by rivkode** [TeamSynergyy/synergy_be#99]
## 📌 Feature Issue

게시글 도메인에 대해 로직을 변경합니다.

- service 클래스를 -> `service 인터페이스, service 구현클래스` 로 구분합니다.
- 객체에 대한 책임을 부여하며 service 인터페이스에서는 객체간의 흐름을 제어하기 위한 코드를 작성합니다.
- 비즈니스 로직을 보았을때 비즈니스의 흐름을 이해할 수 있도록 합니다.

## To-do

- [x] `service 인터페이스, service 구현클래스` 로 구분하기
- [x] `repository` 에 접근하기 위해 reader 클래스 생성
- [x] 객체의 책임과 역할 정의하기
- [x] 동일하게 기능적으로 동작하도록 리팩터링하기

## 최근 고민

강의를 수강하며 해당 개념은 이해를 하였으나 기존 코드의 양과 복잡성이 높아 이를 리팩토링 하는것이 옳은지, 혹은 다른 프로젝트를 진행 시 적용할지에 대한 고민을 하고 있습니다.

## ETC

Business Layer 인자 처리에 대한 내용이 궁금하여 인프런 강의의 강사님께 질문글을 올림.

[Business Layer 인자 처리](https://www.inflearn.com/questions/1266966/business-layer-%EC%9D%B8%EC%9E%90-%EC%B2%98%EB%A6%AC)

```
해당 질문, 답변 요약

질문
새롭게 나오게된 targetStore, usePoint 객체들을

클라이언트로부터 전달되는 presentation layer 에서 바로 전달받는 것을 기대하셨는지
아니면 리팩토링 전과 같이 payRequest 로 controller에서 전달 받은 뒤 다른 layer (business 혹은 presentation) 에서 dto 로 변경한 뒤 businessPay() 메서드를 호출하여 인자를 입력해주는 것을 기대하셨는지
아니면 다른 방법으로 진행이 되는지 

답변

외부 랑 가장 가까운 Presentation Layer 에서 PayRequest 를 받고 Presentation Layer 에서 Business Layer 로 가기전에 Business, Implement Layer 의 객체로 변환을 하고 넘겨준다고 이해하시면 될 것 같습니다.
```

[비즈니스 로직에 대한 생각 - 블로그 업데이트](https://velog.io/@rivkode/%EB%B9%84%EC%A6%88%EB%8B%88%EC%8A%A4-%EB%A1%9C%EC%A7%81%EC%97%90-%EB%8C%80%ED%95%9C-%EC%83%9D%EA%B0%81)
